export const globalExclude: Array<string> = [
    "CORK PULL",
    "Hot Dog",
    "HOT DOG",
    "HOT DOG MEAL ",
    "Envelope Game NICA Angels ",
    "NICA ANGELS RAFFLE TICKET ",
    "PIZZA SLICE ",
    "PREMIUM RED WINE",
    "PREMIUM WHITE WINE ",
    "RED WINE",
    "SACRED SAND T-SHIRT",
    "SACRED SAND T-SHIRT ",
    "Silent Auction",
    "The Voice ",
    "The Voice (plain Cover) ",
    "WHITE WINE",
    "WINE DONATION RED",
    "WINE DONATION WHITE",
    "Wine Order",
    "WINE TO WATER CASH DOOR SALES",
];

export const donationsExclude: Array<string> = [
    "coffee pot",
    "coffee donation",
    "card ministry donation",
    "donation (general giving)",
    "next gen events",
    "nica angels donation",
    "ukraine donations",
    "regular",
    "caramel",
    "decaf",
    "french vanilla",
    "hazelnut",
];