// Item Image Mappings
export const imagesCategory: Record<string, string> = {
    bagels: "/img/category-bagels.png",
    "baked goods": "/img/category-baked_goods.png",
    barista: "/img/category-barista.png",
    donations: "/img/category-donations.png",
    "drink cooler": "/img/category-drink_cooler.png",
    "nica angels": "/img/category-nica.png",
    snacks: "/img/category-snacks.png",
    wine: "/img/category-wine.png",
};

export const imagesCoffee: Record<string, string> = {
    regular: "/img/coffee-regular.png",
    hazelnut: "/img/coffee-hazelnut.png",
    "french vanilla": "/img/coffee-vanilla.png",
    caramel: "/img/coffee-caramel.png",
    decaf: "/img/coffee-decaf.png",
};

export const imagesDefault = "/img/item-default.png";

// Item Name Mappings
export const itemNameMap: Record<string, string> = {
    "cup of coffee": "coffee donation",
    "hot tea": "coffee donation",
    "cookies (2 for $1)": "cookies",
    "cookies (2 for $1.00)": "cookies",
    "hot chocolate": "hot cocoa",
    "donation": "donation (general giving)",
    "cake ball / pop": "cake pop",
    "chai tea latte": "chai latte",
    "chai tea": "chai latte",
    "iced chai latte": "chai latte",
    "iced latte": "latte",
    "cup of milk": "milk",
    "custom amount": "coffee donation",
    "tazo tea": "coffee donation",
    "danish / turnover": "danish",
    "holiday cookie": "cookies",
    "juice box": "juice",
    "organic milk": "milk",
    "starbucks frappuccino": "frappuccino",
    "hot dog meal": "hot dog",
    "wine donation white": "white wine",
    "wine donation red": "red wine",
    "premium white wine": "white wine",
    "premium red wine": "red wine",
    "iced coffee": "americano",
};

export const itemCategoryMap: Record<string, string> = {
    "hot drinks": "barista",
    "cold drinks": "drink cooler",
    "bakery items": "baked goods",
}

export const itemCategoryAssignment: Record<string, string> = {
    "apple juice": "drink cooler",
    "chips": "snacks",
    "breakfast pizza": "baked goods",
    "pop": "drink cooler",
    "scone": "baked goods",
    "donut": "baked goods",
    "cupcake": "baked goods",
    "frappuccino": "drink cooler",
    "powerade": "drink cooler",
    "orange juice": "drink cooler",
    "vitamin water": "drink cooler",
    "unsweetened tea": "drink cooler",
    "steamer": "barista",
}


// 1. Remap modifier names
// 2. Remap modifier category names
// 3. Assign deleted modifiers to category

// Global Modifier Selection Renaming 
export const modifierGlobalNameMap: Record<string, string> = {
    "no whip": "no add-on",
    "whip": "whipped cream",
    "whip cream": "whipped cream",
    "marshmallow": "marshmallows",
    "mocha (chocolate sauce)": "mocha",
    "special": "other",
    "plain ol boring hot cocoa for linda": "no add-on",
    "plain ol boring hot chocolate for linda": "no add-on",    
    "soy": "soy milk",    
    "oat": "oat milk",    
    "whole": "whole milk",    
    "skim": "skim milk",    
    "2%": "2% milk",    
    "2 %": "2% milk", 
    "regular (no syrup)": "no flavor",  
};

export const modifierItemNameMap: Record<string, Record<string, string>> = {
        "bagel": {
            "asiago cheese": "cheese",
            "wheat": "honey wheat",
            "everything but the bagel seasonings": "everything seasoning",
            "reg cream cheese": "regular cream cheese",
            "cream cheese: regular": "regular cream cheese",
            "cream cheese - regular": "regular cream cheese",
            "cream cheese: strawberry": "strawberry cream cheese",
            "cream cheese - strawberry": "strawberry cream cheese",
            "strawberry": "strawberry cream cheese",
            "cream cheese: veggie": "veggie cream cheese",
            "cream cheese - veggie": "veggie cream cheese",
            "chive & onion": "chive & onion cream cheese",
            "cream cheese: chive & onion": "chive & onion cream cheese",
            "cream cheese - chive & onion": "chive & onion cream cheese",
            "butter & cream cheese": "regular cream cheese, butter",
            "uncooked": "untoasted",
            "janes bagel double toasted with butter and cream cheese": "double toasted",
            "john's bagel after first service lots of butter": "toasted",
            "john's bagel after first service": "toasted",
            "johns bagel after first service": "toasted",
            "the jon doyle bagel cheese bagel with chive or veggie cream cheese and bagel sprinkles": "toasted",
            "the doyel slacker bagel cheese bagel with chive or veggie cream cheese and bagel sprinkles": "toasted",
            
        },
        "muffin": {
            "double chocolate": "chocolate",
            "blueberry crumb": "blueberry",
            "pumpkin swirl": "pumpkin",
        },    
        "hot cocoa": {
            "regular (16oz)": "large (16oz)",
            "none": "no add-on",
            "plain": "no flavor",
            "chocolate strawberry": "strawberry",
        },    
        "latte": {
            "chris mocha": "mocha",
            "pumpkin": "pumpkin spice",
            "none": "no add-on",
            "regular": "no flavor",
            "regular (no syrup)": "no flavor",
            "extra shot of espresso": "xtra shot espresso",
        },   
        "cappuccino": {
            "extra shot of espresso": "xtra shot espresso",
            "none": "no add-on",
            "regular": "no flavor",
            "cinnamon": "cinnamon powder",
        },   
        "chai latte": {
            "cinnamon": "cinnamon powder",
            "extra shot of espresso": "xtra shot espresso",
            "none": "no add-on",
            "regular": "no flavor",
        },   
        "juice": {
            "red": "fruit punch",
            "super fruit punch": "fruit punch",
            "purple": "grape",
            "goodness grapeness": "grape",
            "berry good lemonade": "berry",
            "blue": "berry",
            "apple ever after": "apple",
        },    
};

export const modifierCategoryMap: Record<string, string> = {
    "pop flavor": "flavor",
    "juice flavor": "flavor",
    "gatorade flavor": "flavor",
    "sparkling ice flavor": "flavor",
    "iced tea variety": "variety",
    "latte flavors & additions": "flavor",
    "drink topping": "add-ons",
    "add-ons (chai)": "add-ons",
    "add-ons (cocoa)": "add-ons",
    "milk options": "milk",
    "size (cocoa)": "size",
    "cookie flavor": "flavor",
    "danish flavor": "flavor",
    "muffin flavor": "flavor",
    "bagel flavor": "flavor",
    "bagel cook type": "toast level",
    "bagel topping": "topping",
    "bagel preparation": "preparation",
    "english muffin cook type": "toast level",
    "english muffin spread": "spread",
    "breakfast sandwich": "modifications",
};

export const modifierSkipped = ["ask for order name"];

export const modifierCategoryAssignment: Record<string, string> = {
    "other": "flavor",
    "regular": "flavor",
    "almond": "flavor",
    "hazelnut praline": "flavor",
    "caramel cookie": "flavor",
    "apple pie": "flavor",
    "white pumpkin": "flavor",
    "pumpkin spice": "flavor",
    "raspberry white chocolate": "flavor",
    "pumpkin cookie dough": "flavor",
    "frosted gingerbread": "flavor",
    "hazelnut breeze": "flavor",
    "peppermint bark": "flavor",
    "irish cream": "flavor",
    caramel: "flavor",
    butterscotch: "flavor",
    mocha: "flavor",
    coconut: "flavor",
    blueberry: "flavor",
    cinnamon: "flavor",
    gingerbread: "flavor",
    "cinnamon raisin": "bagel flavor",
    "honey wheat": "bagel flavor",
    "coffee cake": "muffin flavor",
    "double chocolate": "muffin flavor",
    chocolate: "muffin flavor",
    "pumpkin cream cheese": "topping",
    "blueberry cream cheese": "topping",
    "cream cheese on the side": "topping",
    "apple cinnamon pecan": "muffin flavor",
    "banana nut": "muffin flavor",
    "caramel apple": "muffin flavor",
    "caramel crunch": "muffin flavor",
    "carrot cake": "muffin flavor",
    "chocolate chunk": "muffin flavor",
    "cinnamon crunch": "muffin flavor",
    "cookies & cream": "muffin flavor",
    "triple berry": "muffin flavor",
    "the works": "add-ons",
    "regular cream cheese, butter": "topping",
    "soy milk": "milk",
    "skim milk": "milk",
    "extra shot of espresso": "add-ons",
    "sprinkles": "add-ons",
    "fruit punch": "flavor",
    "berry": "flavor",
    "grape": "flavor",
    "everything seasoning": "topping",
    "oatmeal raisin": "flavor",
    "orange": "flavor",
    "2% milk": "milk",
    "whole milk": "milk",
    "whipped cream": "add-ons",
    "no add-on": "add-ons",
    "cinnamon powder": "add-ons",
    "diet pepsi": "flavor",
    "pepsi": "flavor",
    "crush (orange)": "flavor",
    "diet mountain dew": "flavor",
    "grape raspberry": "flavor",
    "purple (grape)": "flavor",
    "large (16oz)": "size",
};
