// Item Image Mappings
export const imagesCategory: Record<string, string> = {
    toaster: "/img/category-toaster.png",
    "baked goods": "/img/category-baked_goods.png",
    barista: "/img/category-barista.png",
    donations: "/img/category-donations.png",
    "drink cooler": "/img/category-drink_cooler.png",
    "nica angels": "/img/category-nica.png",
    snacks: "/img/category-snacks.png",
    wine: "/img/category-wine.png",
};

export const imagesCoffee: Record<string, string> = {
    regular: "/img/coffee-regular.png",
    hazelnut: "/img/coffee-hazelnut.png",
    "french vanilla": "/img/coffee-vanilla.png",
    caramel: "/img/coffee-caramel.png",
    decaf: "/img/coffee-decaf.png",
};

export const imagesDiscount: Record<string, string> = {
    "cafe volunteer": "volunteer_activism",
    comp: "money_off",
    "cookie card": "cookie",
    "bagel card": "adjust",
    "loyalty card": "loyalty",
    "custom discount": "price_change",
    musician: "artist",
    sample: "glass_cup",
};

export const imagesDefault = "/img/item-default.png";

// Item Name Mappings
export const itemNameMap: Record<string, string> = {
    "cup of coffee": "coffee donation",
    "hot tea": "coffee donation",
    "cookies (2 for $1)": "cookies",
    "cookies (2 for $1.00)": "cookies",
    "hot chocolate": "hot cocoa",
    donation: "donation (general giving)",
    "cake ball / pop": "cake pop",
    "chai tea latte": "chai latte",
    "chai tea": "chai latte",
    "iced chai latte": "chai latte",
    "iced latte": "latte",
    "cup of milk": "milk",
    "custom amount": "coffee donation",
    "tazo tea": "coffee donation",
    "danish / turnover": "danish",
    "holiday cookie": "cookies",
    "juice box": "juice",
    "organic milk": "milk",
    "starbucks frappuccino": "frappuccino",
    "hot dog meal": "hot dog",
    "wine donation white": "white wine",
    "wine donation red": "red wine",
    "premium white wine": "white wine",
    "premium red wine": "red wine",
    "iced coffee": "americano",
};

export const itemCategoryMap: Record<string, string> = {
    "hot drinks": "barista",
    "cold drinks": "drink cooler",
    "bakery items": "baked goods",
    bagels: "toaster",
};

export const itemCategoryAssignment: Record<string, string> = {
    americano: "barista",
    "apple juice": "drink cooler",
    "chai latte": "barista",
    "iced chai latte": "barista",
    "chai tea": "barista",
    chips: "snacks",
    "breakfast pizza": "baked goods",
    pop: "drink cooler",
    powerade: "drink cooler",
    scone: "baked goods",
    donut: "baked goods",
    cupcake: "baked goods",
    frappuccino: "drink cooler",
    "la croix": "drink cooler",
    "orange juice": "drink cooler",
    "vitamin water": "drink cooler",
    "unsweetened tea": "drink cooler",
    steamer: "barista",
};

// 1. Remap modifier names
// 2. Remap modifier category names
// 3. Assign deleted modifiers to category

// Global Modifier Selection Renaming
export const modifierGlobalNameMap: Record<string, string> = {
    "no whip": "no add-on",
    whip: "whipped cream",
    "whip cream": "whipped cream",
    marshmallow: "marshmallows",
    "mocha (chocolate sauce)": "mocha",
    special: "other",
    soy: "soy milk",
    oat: "oat milk",
    whole: "whole milk",
    skim: "skim milk",
    "2%": "2% milk",
    "2 %": "2% milk",
    "regular (no syrup)": "no flavor",
};

export const modifierItemNameMap: Record<string, Record<string, string>> = {
    bagel: {
        "asiago cheese": "cheese",
        wheat: "honey wheat",
        "everything but the bagel seasonings": "everything seasoning",
        "reg cream cheese": "regular cream cheese",
        "cream cheese: regular": "regular cream cheese",
        "cream cheese - regular": "regular cream cheese",
        "cream cheese: strawberry": "strawberry cream cheese",
        "cream cheese - strawberry": "strawberry cream cheese",
        strawberry: "strawberry cream cheese",
        "cream cheese: veggie": "veggie cream cheese",
        "cream cheese - veggie": "veggie cream cheese",
        "chive & onion": "chive & onion cream cheese",
        "cream cheese: chive & onion": "chive & onion cream cheese",
        "cream cheese - chive & onion": "chive & onion cream cheese",
        "butter & cream cheese": "regular cream cheese, butter",
        uncooked: "untoasted",
        "janes bagel double toasted with butter and cream cheese":
            "double toasted",
        "john's bagel after first service lots of butter": "toasted",
        "john's bagel after first service": "toasted",
        "johns bagel after first service": "toasted",
        "the jon doyle bagel cheese bagel with chive or veggie cream cheese and bagel sprinkles":
            "toasted",
        "the doyel slacker bagel cheese bagel with chive or veggie cream cheese and bagel sprinkles":
            "toasted",
    },
    muffin: {
        "blueberry crumb": "blueberry",
        "pumpkin swirl": "pumpkin",
        chocolate: "double chocolate",
    },
    "hot cocoa": {
        "regular (16oz)": "large (16oz)",
        none: "no add-on",
        plain: "no flavor",
        "chocolate strawberry": "strawberry",
        "plain ol boring hot cocoa for linda": "no add-on",
        "plain ol boring hot chocolate for linda": "no add-on",
    },
    latte: {
        "chris mocha": "mocha",
        pumpkin: "pumpkin spice",
        none: "no add-on",
        regular: "no flavor",
        "regular (no syrup)": "no flavor",
        "extra shot of espresso": "xtra shot espresso",
    },
    cappuccino: {
        "extra shot of espresso": "xtra shot espresso",
        none: "no add-on",
        regular: "no flavor",
        cinnamon: "cinnamon powder",
    },
    "chai latte": {
        cinnamon: "cinnamon powder",
        "extra shot of espresso": "xtra shot espresso",
        none: "no add-on",
        regular: "no flavor",
    },
    juice: {
        red: "fruit punch",
        "super fruit punch": "fruit punch",
        purple: "grape",
        "goodness grapeness": "grape",
        "berry good lemonade": "berry",
        blue: "berry",
        "apple ever after": "apple",
    },
    powerade: {
        red: "fruit punch",
        blue: "berry blast",
        purple: "grape",
    },
    "red wine": {
        cab: "cabernet",
    },
    "white wine": {
        chard: "chardonnay",
    },
    pop: {
        orange: "crush (orange)",
    },
};

export const modifierCategoryMap: Record<string, string> = {
    "add-ons (chai)": "add-ons",
    "add-ons (cocoa)": "add-ons",
    "bagel cook type": "toast level",
    "bagel flavor": "flavor",
    "bagel preparation": "preparation",
    "bagel topping": "topping",
    "breakfast sandwich": "modifications",
    "cookie flavor": "flavor",
    "cake pop": "flavor",
    "danish flavor": "flavor",
    "drink topping": "add-ons",
    "english muffin cook type": "toast level",
    "english muffin spread": "spread",
    "gatorade flavor": "flavor",
    "iced tea variety": "variety",
    "juice flavor": "flavor",
    "latte flavors & additions": "flavor",
    "milk options": "milk",
    "muffin flavor": "flavor",
    "pop flavor": "flavor",
    "size (cocoa)": "size",
    "sparkling ice flavor": "flavor",
};

export const modifierSkipped = ["ask for order name"];

export const modifierCategoryAssignment: Record<string, string> = {
    "chocolate chip": "flavor",
    gingerbread: "flavor",
    "large (16oz)": "size",
    "lemon apricot": "flavor",
    other: "flavor",
    regular: "flavor",
    vanilla: "flavor",
    // Latte & Cocoa Flavors
    almond: "flavor",
    "apple pie": "flavor",
    blueberry: "flavor",
    butterscotch: "flavor",
    caramel: "flavor",
    "caramel cookie": "flavor",
    cinnamon: "flavor",
    coconut: "flavor",
    "frosted gingerbread": "flavor",
    "hazelnut breeze": "flavor",
    "hazelnut praline": "flavor",
    "lucky pistachio": "flavor",
    "irish cream": "flavor",
    mocha: "flavor",
    "peppermint bark": "flavor",
    "pumpkin cookie dough": "flavor",
    "pumpkin spice": "flavor",
    "raspberry white chocolate": "flavor",
    "white peppermint": "flavor",
    "white pumpkin": "flavor",
    // Bagel Flavors
    "cinnamon raisin": "bagel flavor",
    "honey wheat": "bagel flavor",
    // Bagel Toppings
    "blueberry cream cheese": "topping",
    "everything seasoning": "topping",
    "cream cheese on the side": "topping",
    "pumpkin cream cheese": "topping",
    "regular cream cheese, butter": "topping",
    // Muffin Flavors
    "apple cinnamon pecan": "muffin flavor",
    "banana nut": "muffin flavor",
    "caramel apple": "muffin flavor",
    "caramel crunch": "muffin flavor",
    "carrot cake": "muffin flavor",
    "chocolate chunk": "muffin flavor",
    "cinnamon crunch": "muffin flavor",
    "coffee cake": "muffin flavor",
    "cookies & cream": "muffin flavor",
    "double chocolate": "muffin flavor",
    "triple berry": "muffin flavor",
    // Milk
    "2% milk": "milk",
    "skim milk": "milk",
    "soy milk": "milk",
    "whole milk": "milk",
    // Add-Ons
    "cinnamon powder": "add-ons",
    "extra shot of espresso": "add-ons",
    "no add-on": "add-ons",
    sprinkles: "add-ons",
    "the works": "add-ons",
    "whipped cream": "add-ons",
    // Pop Flavors
    coke: "flavor",
    "diet coke": "flavor",
    "diet pepsi": "flavor",
    pepsi: "flavor",
    "crush (orange)": "flavor",
    "diet mountain dew": "flavor",
    "mountain dew": "flavor",
    "root beer": "flavor",
    "diet root beer": "flavor",
    sprite: "flavor",
    "diet sprite": "flavor",
    "dr pepper": "flavor",
    "diet dr pepper": "flavor",
    // Cookie Flavors
    "oatmeal raisin": "flavor",
    // Drink Flaors
    apple: "flavor",
    berry: "flavor",
    "berry blast": "flavor",
    "coconut pineapple": "flavor",
    "fruit punch": "flavor",
    grape: "flavor",
    "grape raspberry": "flavor",
    lemon: "flavor",
    lemonade: "flavor",
    orange: "flavor",
    "power c": "flavor",
    "purple (grape)": "flavor",
    red: "flavor",
    revive: "flavor",
    "white (glacier cherry)": "flavor",
    xxx: "flavor",
    // Wine Varieties
    blend: "variety",
    cabernet: "variety",
    chardonnay: "variety",
    "pinot noir": "variety",
    riesling: "variety",
    sparkling: "variety",
    // Pizza Toppings
    sausage: "flavor",
    cheese: "flavor",
    pepperoni: "flavor",
};
